In [1]:
#library import
import numpy as np

In [2]:
#play with basic numpy arrays
a = np.array([1,2,3])   #create 3x1 array

print(type(a))   #print data type

print(a.shape)   #print shape of array

print(a[0])   #print first element of array

<class 'numpy.ndarray'>
(3,)
1


In [4]:
# 2 x 2 array
b = np.array ([[1,2],[3,4]])

print(b.shape)

print(b[0,1])

(2, 2)
2


In [8]:
# generate numbers for an array

# create 2 x 3 array with zeros
d = np.zeros((2,3))

print(d)

# create 2 x 2 array with all 9s
f = np.full((2,2), 9)

print(f)

# create 3 x 3 array with random numbers
g = np.random.random((3,3))
# How do you set random integers???

print(g)

[[0. 0. 0.]
 [0. 0. 0.]]
[[9 9]
 [9 9]]
[[0.81937747 0.02088581 0.41577291]
 [0.15380597 0.3494412  0.93389928]
 [0.39721222 0.95288762 0.10980099]]


Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [16]:
# Array slicing

h = np.array([[1,2,3], [4,5,6], [7,8,9]])
#print(h)

i = h[:2, 1:3]

print(i)

[[2 3]
 [5 6]]
