In [1]:
#library import
import numpy as np

In [2]:
#play with basic numpy arrays
a = np.array([1,2,3])   #create 3x1 array

print(type(a))   #print data type

print(a.shape)   #print shape of array

print(a[0])   #print first element of array

<class 'numpy.ndarray'>
(3,)
1


In [3]:
# 2 x 2 array
b = np.array ([[1,2],[3,4]])

print(b.shape)

print(b[0,1])

(2, 2)
2


In [4]:
# generate numbers for an array

# create 2 x 3 array with zeros
d = np.zeros((2,3))

print(d)

# create 2 x 2 array with all 9s
f = np.full((2,2), 9)

print(f)

# create 3 x 3 array with random numbers
g = np.random.random((3,3))
# How do you set random integers???

print(g)

[[0. 0. 0.]
 [0. 0. 0.]]
[[9 9]
 [9 9]]
[[0.29626581 0.59233571 0.82308728]
 [0.51423285 0.43857264 0.66382301]
 [0.20120796 0.0457122  0.24935347]]


Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [5]:
# Array slicing

h = np.array([[1,2,3], [4,5,6], [7,8,9]])
#print(h)

i = h[:2, 1:3]

print(i)

# I NEED TO REVIEW THIS MORE

[[2 3]
 [5 6]]


In [7]:
# Datatypes in Arrays

#This will be processed as integer
j = np.array([1,2])
print(j.dtype)

#This will be processed as a float
k = np.array ([1.0, 2.0])
print(k.dtype)

#Set datatype with dtype
l = np.array([1.0, 2.0], dtype = np.int64)
print(l.dtype)

int32
float64
int64


#Array Math

In [16]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#Sum of elements; sum of the array
print (x + y)
print(np.add(x,y))
#Is this different?  If so, how?

#Element difference
print(x - y)
print(np.subtract(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [19]:
#Product of elements
print(x * y)
print(np.multiply(x,y))

#Division of elements
print(x/y)
print(np.divide(x,y))

#Square root of elements
print(np.sqrt(x))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [26]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
# sum of all of the elements for x
print(np.sum(x))

#sum of the numbers in a column
print(np.sum(x, axis = 0))

#sum of the numbers in a row
print(np.sum(x, axis = 1))

#compute mean of ALL elements
print(np.mean(x))

#compute mean of numbers in a column
print(np.mean(x, axis = 0))

#compute mean of numbers in each row
print(np.mean(x, axis = 1))

10.0
[4. 6.]
[3. 7.]
2.5
[2. 3.]
[1.5 3.5]


#SciPy
Using the stats sub modules
This contains a large number of probability distributions as well as a growing library of statistical functions

- Continuous and Dsicrete Distributions
- Descriptive Statistics
- Statical Test (T-Test)


In [28]:
from scipy import stats
import numpy as np

In [29]:
#Print random variables with a normal distribution
print(stats.norm.rvs(size=10))

[-1.22838052  1.12432185  1.71106134  0.71510687  0.22690122  0.11924696
  0.07055393 -0.28746706 -1.12708225  0.58310287]


In [30]:
np.random.seed(282)

# Generate 1000 numbers in a T distribution
x = stats.t.rvs(10, size=1000)

# What is the first 10 for?

In [31]:
print(x.min())

print(x.max())

print(x.mean())

print(x.var())

stats.describe(x)

-4.352407464829776
3.2692587786535547
0.028814524286841475
1.3359198357478759


DescribeResult(nobs=1000, minmax=(-4.352407464829776, 3.2692587786535547), mean=0.028814524286841475, variance=1.3372570928407166, skewness=-0.009988147310210471, kurtosis=0.4794481198618712)

#Kurtosis
Measure of the "tailedness" of the probability distribution